name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install

      - name: Configure environment
        run: |
          echo "HYDE_RC_RUNNER_PATH=/tmp/hyde-rc-runner" >> $GITHUB_ENV
          if [ ${{ github.event_name }} == 'push' ]; then
            echo "HYDE_RC_RUNNER_BRANCH=master" >> $GITHUB_ENV
          else
            echo "HYDE_RC_BRANCH=$GITHUB_SHA" >> $GITHUB_ENV
          fi

      - name: Set up test runner
        run: php -r 'require_once __DIR__."/vendor/autoload.php"; \Hyde\RealtimeCompiler\Tests\Integration\IntegrationTestCase::setUpTestRunner();'

      - name: Run tests with PHPUnit
        run: vendor/bin/phpunit --colors=always
